# Generated by Django 4.2.5 on 2023-10-06 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0005_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
